--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-02-25 07:42:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 235 (class 1259 OID 16775)
-- Name: dinosaur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dinosaur (
    id integer NOT NULL,
    name character varying NOT NULL,
    species character varying NOT NULL,
    gender character varying NOT NULL,
    max_speed real,
    weight real,
    height real,
    enclosure_id integer
);


ALTER TABLE public.dinosaur OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16774)
-- Name: dinosaur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dinosaur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dinosaur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16586)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id integer NOT NULL,
    name character varying NOT NULL,
    gender character varying NOT NULL,
    age integer,
    "position" character varying NOT NULL,
    experience integer
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16526)
-- Name: employee_exhibit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_exhibit (
    employee_id integer NOT NULL,
    exhibit_id integer NOT NULL
);


ALTER TABLE public.employee_exhibit OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16585)
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16491)
-- Name: enclosure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enclosure (
    id integer NOT NULL,
    square real NOT NULL,
    location character varying NOT NULL,
    height real,
    capacity integer
);


ALTER TABLE public.enclosure OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16523)
-- Name: enclosure_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enclosure_employee (
    enclosure_id integer NOT NULL,
    employee_id integer NOT NULL
);


ALTER TABLE public.enclosure_employee OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16490)
-- Name: enclosure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enclosure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enclosure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16513)
-- Name: exhibit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exhibit (
    id integer NOT NULL,
    name character varying NOT NULL,
    description text,
    type character varying,
    date date
);


ALTER TABLE public.exhibit OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16512)
-- Name: exhibit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exhibit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exhibit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16475)
-- Name: food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food (
    id integer NOT NULL,
    price money NOT NULL,
    species character varying,
    composition text NOT NULL,
    amount real
);


ALTER TABLE public.food OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16520)
-- Name: food_dinosaur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_dinosaur (
    food_id integer NOT NULL,
    dinosaur_id integer NOT NULL
);


ALTER TABLE public.food_dinosaur OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16474)
-- Name: food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16783)
-- Name: tour; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour (
    id integer NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    duration time without time zone,
    price money NOT NULL,
    visitor_id integer
);


ALTER TABLE public.tour OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16532)
-- Name: tour_enclosure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour_enclosure (
    tour_id integer NOT NULL,
    enclosure_id integer NOT NULL
);


ALTER TABLE public.tour_enclosure OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16529)
-- Name: tour_exhibit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour_exhibit (
    tour_id integer NOT NULL,
    exhibit_id integer NOT NULL
);


ALTER TABLE public.tour_exhibit OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16782)
-- Name: tour_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tour ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16505)
-- Name: visitor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.visitor (
    id integer NOT NULL,
    name character varying NOT NULL,
    gender character varying NOT NULL,
    age integer,
    ticket integer NOT NULL
);


ALTER TABLE public.visitor OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16504)
-- Name: visitor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.visitor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visitor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4960 (class 0 OID 16775)
-- Dependencies: 235
-- Data for Name: dinosaur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dinosaur (id, name, species, gender, max_speed, weight, height, enclosure_id) FROM stdin;
1	Джек	Тиранозавр	Муж	55.3	7800	4.1	26
2	Ларри	Диплодок	Жен	60	6700	5.6	9
3	Рекс	Тиранозавр	Муж	50.5	8000	4.2	13
4	Стелла	Трицератопс	Жен	30	6000	3	18
5	Бруно	Велоцираптор	Муж	65	150	1.8	2
6	Луна	Стегозавр	Жен	25	5000	4.5	9
7	Спарки	Птеродактиль	Муж	80	50	1.2	25
8	Тиша	Брахиозавр	Жен	20	30000	12	18
9	Гром	Анкилозавр	Муж	15	6000	2.5	17
10	Зоя	Паразауролоф	Жен	40	2500	3.8	20
11	Рокки	Аллозавр	Муж	55	2000	3.5	4
12	Мия	Галлимим	Жен	70	450	2	13
13	Тор	Карнотавр	Муж	60	1500	3	17
14	Эльза	Дилофозавр	Жен	45	400	2.2	5
15	Зевс	Спинозавр	Муж	35	7000	5	25
16	Флора	Игуанодон	Жен	30	3000	3.2	13
17	Блейд	Дейноних	Муж	75	100	1.5	15
18	Лили	Овираптор	Жен	50	80	1	27
19	Макс	Мозазавр	Муж	40	15000	10	9
20	Нора	Археоптерикс	Жен	60	1	0.5	16
21	Дейзи	Компсогнат	Жен	65	3	0.7	15
22	Гизмо	Протоцератопс	Муж	25	400	1.8	8
23	Руби	Цератозавр	Жен	45	1000	2.5	27
24	Оливер	Пахицефалозавр	Муж	30	1200	2	12
25	Астра	Эдмонтозавр	Жен	35	3000	3.5	6
26	Бакс	Майазавр	Муж	20	2500	3	25
27	Чарли	Троодон	Муж	70	50	1	7
\.


--
-- TOC entry 4958 (class 0 OID 16586)
-- Dependencies: 233
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (id, name, gender, age, "position", experience) FROM stdin;
1	Иван Петров	Мужской	35	Смотритель	10
2	Мария Иванова	Женский	28	Ветеринар	5
3	Алексей Смирнов	Мужской	40	Инженер	15
4	Елена Кузнецова	Женский	32	Биолог	8
5	Дмитрий Волков	Мужской	29	Охранник	6
6	Ольга Белова	Женский	27	Администратор	4
7	Сергей Новиков	Мужской	45	Директор	20
8	Анна Морозова	Женский	30	Ученый	7
9	Павел Козлов	Мужской	33	Техник	9
10	Татьяна Лебедева	Женский	26	Лаборант	3
11	Николай Соколов	Мужской	38	Смотритель	12
12	Юлия Воробьева	Женский	31	Ветеринар	6
13	Андрей Павлов	Мужской	34	Инженер	10
14	Наталья Семенова	Женский	29	Биолог	5
15	Артем Михайлов	Мужской	42	Охранник	14
16	Екатерина Федорова	Женский	36	Администратор	11
17	Виктор Григорьев	Мужской	39	Директор	18
18	Людмила Егорова	Женский	28	Ученый	4
19	Игорь Захаров	Мужской	37	Техник	13
20	Светлана Николаева	Женский	33	Лаборант	8
21	Роман Борисов	Мужской	31	Смотритель	7
22	Марина Алексеева	Женский	27	Ветеринар	3
23	Вадим Тимофеев	Мужской	44	Инженер	16
24	Алина Степанова	Женский	30	Биолог	6
25	Георгий Макаров	Мужской	35	Охранник	10
26	Вера Дмитриева	Женский	29	Администратор	5
27	Станислав Орлов	Мужской	41	Директор	17
\.


--
-- TOC entry 4954 (class 0 OID 16526)
-- Dependencies: 229
-- Data for Name: employee_exhibit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_exhibit (employee_id, exhibit_id) FROM stdin;
1	2
2	8
3	14
4	19
5	6
6	11
7	3
8	15
9	1
10	22
11	27
12	4
13	10
14	25
15	9
16	17
17	5
18	12
19	20
20	24
21	16
22	21
23	7
24	18
25	13
26	26
27	23
\.


--
-- TOC entry 4947 (class 0 OID 16491)
-- Dependencies: 222
-- Data for Name: enclosure; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enclosure (id, square, location, height, capacity) FROM stdin;
1	500	Северная зона	10	5
2	300	Южная зона	8	3
3	450	Восточная зона	9.5	4
4	600	Западная зона	12	6
5	350	Центральная зона	7	2
6	400	Северо-Восточная зона	8.5	4
7	550	Юго-Западная зона	11	5
8	480	Северо-Западная зона	9	3
9	700	Юго-Восточная зона	13	7
10	320	Центрально-Северная зона	6.5	2
11	380	Центрально-Южная зона	7.5	3
12	420	Восточно-Северная зона	8	4
13	470	Западно-Южная зона	9	5
14	530	Северо-Центральная зона	10.5	6
15	580	Юго-Центральная зона	11.5	7
16	620	Восточно-Южная зона	12.5	8
17	670	Западно-Северная зона	13.5	9
18	720	Центрально-Восточная зона	14	10
19	770	Центрально-Западная зона	15	11
20	800	Северо-Южная зона	16	12
21	850	Юго-Северная зона	17	13
22	900	Восточно-Западная зона	18	14
23	950	Западно-Восточная зона	19	15
24	1000	Центрально-Северо-Восточная зона	20	16
25	1050	Центрально-Юго-Западная зона	21	17
26	1100	Северо-Западно-Южная зона	22	18
27	1150	Юго-Восточно-Северная зона	23	19
\.


--
-- TOC entry 4953 (class 0 OID 16523)
-- Dependencies: 228
-- Data for Name: enclosure_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enclosure_employee (enclosure_id, employee_id) FROM stdin;
1	19
2	5
3	22
4	14
5	27
6	10
7	18
8	3
9	11
10	24
11	1
12	16
13	25
14	6
15	12
16	23
17	9
18	15
19	7
20	20
21	4
22	2
23	17
24	8
25	13
26	21
27	26
\.


--
-- TOC entry 4951 (class 0 OID 16513)
-- Dependencies: 226
-- Data for Name: exhibit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exhibit (id, name, description, type, date) FROM stdin;
1	Окаменелость трилобита	Окаменелость древнего морского членистоногого, возрастом около 500 миллионов лет.	Палеонтология	2023-01-01
2	Метеорит Альенде	Фрагмент метеорита, упавшего в Мексике в 1969 году. Содержит древнейшее вещество Солнечной системы.	Астрономия	2023-02-15
3	Мумия фараона	Мумия древнеегипетского фараона, сохранившаяся благодаря уникальным методам бальзамирования.	Археология	2023-03-10
4	Розеттский камень	Камень с текстом на трех языках, который помог расшифровать древнеегипетские иероглифы.	История	2023-04-05
5	Скелет тираннозавра	Полный скелет хищного динозавра, одного из самых известных представителей мелового периода.	Палеонтология	2023-05-20
6	Античный амфор	Древнегреческая амфора, использовавшаяся для хранения вина и масла.	Археология	2023-06-12
7	Лунный камень	Образец лунного грунта, доставленный на Землю в ходе миссии "Аполлон-11".	Астрономия	2023-07-18
8	Древний свиток	Свиток с текстом из древней библиотеки, содержащий исторические записи.	История	2023-08-22
9	Окаменелое дерево	Окаменелость древнего дерева, возрастом около 200 миллионов лет.	Палеонтология	2023-09-30
10	Статуя Будды	Древняя статуя Будды, созданная в Индии около 2000 лет назад.	Археология	2023-10-14
11	Фрагмент Великой Китайской стены	Каменный блок из Великой Китайской стены, символизирующий древнюю оборонительную систему.	История	2023-11-05
12	Кость мамонта	Окаменелая кость древнего мамонта, найденная в Сибири.	Палеонтология	2023-12-01
13	Древний компас	Один из первых магнитных компасов, использовавшихся для навигации.	История	2024-01-10
14	Окаменелость аммонита	Окаменелость древнего моллюска, жившего в морях мезозойской эры.	Палеонтология	2024-02-15
15	Римская монета	Древнеримская монета времен Юлия Цезаря.	Археология	2024-03-20
16	Фрагмент Стоунхенджа	Камень из знаменитого мегалитического сооружения в Англии.	История	2024-04-25
17	Окаменелость ихтиозавра	Окаменелость древнего морского рептилии, похожего на дельфина.	Палеонтология	2024-05-30
18	Древний глобус	Один из первых географических глобусов, созданный в XVI веке.	История	2024-06-05
19	Египетский саркофаг	Древний саркофаг с изображениями богов и иероглифами.	Археология	2024-07-10
20	Окаменелость птеродактиля	Окаменелость крылатого динозавра, жившего в мезозойскую эру.	Палеонтология	2024-08-15
21	Древний меч	Меч времен Средневековья, найденный на территории Европы.	История	2024-09-20
22	Окаменелость стегозавра	Окаменелость травоядного динозавра с костяными пластинами на спине.	Палеонтология	2024-10-25
23	Древний свиток Торы	Рукописный свиток Торы, созданный несколько столетий назад.	История	2024-11-30
24	Окаменелость динозавра-велоцираптора	Окаменелость небольшого хищного динозавра.	Палеонтология	2024-12-05
25	Древний китайский фарфор	Ваза времен династии Мин, украшенная традиционными узорами.	Археология	2025-01-10
26	Окаменелость плезиозавра	Окаменелость древнего морского рептилии с длинной шеей.	Палеонтология	2025-02-15
27	Древний шлем викинга	Шлем, принадлежавший древнему воину-викингу.	История	2025-03-20
\.


--
-- TOC entry 4945 (class 0 OID 16475)
-- Dependencies: 220
-- Data for Name: food; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food (id, price, species, composition, amount) FROM stdin;
1	6,23 Br	Мясо птицы, злаки, желуди	Комбинированный	40.7
2	8,47 Br	Свинина	Растительный	80.4
3	7,15 Br	Говядина	Мясной	55.3
4	9,99 Br	Рыба	Белковый	60
5	5,50 Br	Овощи, фрукты	Растительный	75.8
6	10,25 Br	Кости, хрящи	Минеральный	45.6
7	8,75 Br	Зерновые смеси	Злаковый	85.2
8	6,90 Br	Курица, субпродукты	Комбинированный	50.4
9	12,30 Br	Морские водоросли	Растительный	30.7
10	7,80 Br	Ягоды, орехи	Фруктовый	65.9
11	9,45 Br	Кролик	Мясной	40.2
12	11,10 Br	Моллюски, ракообразные	Белковый	55.8
13	6,60 Br	Травы, листья	Растительный	90.1
14	8,20 Br	Яйца, насекомые	Белковый	48.3
15	10,75 Br	Семена, злаки	Злаковый	70.5
16	7,30 Br	Оленина	Мясной	58.7
17	9,85 Br	Морковь, тыква	Овощной	62.4
18	5,95 Br	Костная мука	Минеральный	35.9
19	8,50 Br	Фруктовые смеси	Фруктовый	68.2
20	11,40 Br	Рыбные отходы	Белковый	42.6
21	6,80 Br	Травяные гранулы	Растительный	77.3
22	9,10 Br	Субпродукты птицы	Мясной	53.1
23	12,50 Br	Морские ежи, креветки	Белковый	37.8
24	7,45 Br	Зерно, отруби	Злаковый	80.9
25	10,90 Br	Фруктовые пюре	Фруктовый	59.4
26	8,65 Br	Кости, мясо	Комбинированный	46.7
27	6,25 Br	Листья, побеги	Растительный	88
\.


--
-- TOC entry 4952 (class 0 OID 16520)
-- Dependencies: 227
-- Data for Name: food_dinosaur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_dinosaur (food_id, dinosaur_id) FROM stdin;
1	5
2	12
3	7
4	20
5	11
6	18
7	3
8	14
9	9
10	15
11	22
12	1
13	27
14	4
15	6
16	17
17	10
18	19
19	2
20	25
21	16
22	8
23	13
24	21
25	23
26	26
27	24
\.


--
-- TOC entry 4962 (class 0 OID 16783)
-- Dependencies: 237
-- Data for Name: tour; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tour (id, date, "time", duration, price, visitor_id) FROM stdin;
1	2025-03-06	12:00:00	01:00:00	44,61 Br	11
2	2025-03-13	14:00:00	02:00:00	41,87 Br	15
3	2025-03-13	08:00:00	02:00:00	48,61 Br	18
4	2025-03-11	12:00:00	01:00:00	39,58 Br	20
5	2025-03-16	14:00:00	01:00:00	24,04 Br	3
6	2025-03-19	11:00:00	02:00:00	23,77 Br	24
7	2025-03-20	10:00:00	02:00:00	26,14 Br	18
8	2025-03-06	11:00:00	01:00:00	44,08 Br	13
9	2025-02-26	08:00:00	02:00:00	35,14 Br	1
10	2025-03-24	13:00:00	02:00:00	33,35 Br	18
11	2025-03-02	13:00:00	02:00:00	29,09 Br	13
12	2025-02-26	09:00:00	02:00:00	27,75 Br	11
13	2025-03-15	15:00:00	01:00:00	39,90 Br	17
14	2025-03-11	09:00:00	01:00:00	23,22 Br	1
15	2025-02-27	14:00:00	02:00:00	20,59 Br	12
16	2025-03-08	10:00:00	01:00:00	26,08 Br	19
17	2025-02-25	10:00:00	01:00:00	28,18 Br	17
18	2025-03-08	15:00:00	02:00:00	24,71 Br	6
19	2025-03-09	08:00:00	01:00:00	25,07 Br	21
20	2025-03-08	08:00:00	02:00:00	25,21 Br	5
21	2025-03-12	11:00:00	02:00:00	47,84 Br	8
22	2025-03-22	13:00:00	02:00:00	34,90 Br	22
23	2025-02-25	14:00:00	02:00:00	44,94 Br	24
24	2025-03-20	09:00:00	02:00:00	45,90 Br	27
25	2025-02-26	11:00:00	01:00:00	31,34 Br	18
26	2025-03-03	12:00:00	02:00:00	47,94 Br	17
27	2025-03-18	08:00:00	01:00:00	44,92 Br	17
\.


--
-- TOC entry 4956 (class 0 OID 16532)
-- Dependencies: 231
-- Data for Name: tour_enclosure; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tour_enclosure (tour_id, enclosure_id) FROM stdin;
1	15
2	7
3	23
4	11
5	18
6	4
7	20
8	2
9	25
10	13
11	1
12	21
13	10
14	16
15	19
16	5
17	26
18	3
19	12
20	24
21	9
22	14
23	8
24	27
25	6
26	22
27	17
\.


--
-- TOC entry 4955 (class 0 OID 16529)
-- Dependencies: 230
-- Data for Name: tour_exhibit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tour_exhibit (tour_id, exhibit_id) FROM stdin;
1	9
2	3
3	16
4	22
5	11
6	25
7	4
8	19
9	12
10	7
11	2
12	20
13	14
14	18
15	17
16	6
17	24
18	1
19	8
20	15
21	10
22	26
23	21
24	13
25	5
26	27
27	23
\.


--
-- TOC entry 4949 (class 0 OID 16505)
-- Dependencies: 224
-- Data for Name: visitor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.visitor (id, name, gender, age, ticket) FROM stdin;
1	Иван Иванов	Мужской	25	12345
2	Мария Петрова	Женский	30	12346
3	Алексей Смирнов	Мужской	22	12347
4	Анна Кузнецова	Женский	28	12348
5	Сергей Попов	Мужской	35	12349
6	Елена Соловьёва	Женский	27	12350
7	Дмитрий Васильев	Мужской	33	12351
8	Ольга Павлова	Женский	24	12352
9	Николай Фёдоров	Мужской	29	12353
10	Татьяна Романова	Женский	31	12354
11	Владимир Николаев	Мужской	40	12355
12	Юлия Ковалёва	Женский	26	12356
13	Максим Егоров	Мужской	21	12357
14	Ирина Белова	Женский	32	12358
15	Андрей Сидоров	Мужской	38	12359
16	Ксения Лебедева	Женский	23	12360
17	Роман Григорьев	Мужской	34	12361
18	Виктория Тихонова	Женский	29	12362
19	Артур Захаров	Мужской	36	12363
20	Светлана Михайлова	Женский	30	12364
21	Егор Сафонов	Мужской	27	12365
22	Лариса Смирнова	Женский	25	12366
23	Денис Фролов	Мужской	39	12367
24	Наталья Морозова	Женский	22	12368
25	Станислав Кузьмин	Мужской	28	12369
26	Алёна Костина	Женский	31	12370
27	Павел Громов	Мужской	24	12371
\.


--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 234
-- Name: dinosaur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dinosaur_id_seq', 1, false);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 232
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_id_seq', 1, false);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 221
-- Name: enclosure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enclosure_id_seq', 1, false);


--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 225
-- Name: exhibit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exhibit_id_seq', 1, false);


--
-- TOC entry 4972 (class 0 OID 0)
-- Dependencies: 219
-- Name: food_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_id_seq', 1, false);


--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 236
-- Name: tour_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tour_id_seq', 54, true);


--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 223
-- Name: visitor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.visitor_id_seq', 1, false);


--
-- TOC entry 4758 (class 2606 OID 16781)
-- Name: dinosaur dinosaur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dinosaur
    ADD CONSTRAINT dinosaur_pkey PRIMARY KEY (id);


--
-- TOC entry 4756 (class 2606 OID 16592)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- TOC entry 4750 (class 2606 OID 16497)
-- Name: enclosure enclosure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure
    ADD CONSTRAINT enclosure_pkey PRIMARY KEY (id);


--
-- TOC entry 4754 (class 2606 OID 16519)
-- Name: exhibit exhibit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exhibit
    ADD CONSTRAINT exhibit_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 16481)
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (id);


--
-- TOC entry 4760 (class 2606 OID 16787)
-- Name: tour tour_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour
    ADD CONSTRAINT tour_pkey PRIMARY KEY (id);


--
-- TOC entry 4752 (class 2606 OID 16511)
-- Name: visitor visitor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visitor
    ADD CONSTRAINT visitor_pkey PRIMARY KEY (id);


--
-- TOC entry 4797 (class 2606 OID 16788)
-- Name: dinosaur dinosaur_enclosure_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dinosaur
    ADD CONSTRAINT dinosaur_enclosure_id_fkey FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4776 (class 2606 OID 16623)
-- Name: employee_exhibit employee_exhibit_employee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4777 (class 2606 OID 16683)
-- Name: employee_exhibit employee_exhibit_employee_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_employee_id_fkey1 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4778 (class 2606 OID 16743)
-- Name: employee_exhibit employee_exhibit_employee_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_employee_id_fkey2 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4779 (class 2606 OID 16818)
-- Name: employee_exhibit employee_exhibit_employee_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_employee_id_fkey3 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4780 (class 2606 OID 16560)
-- Name: employee_exhibit employee_exhibit_exhibit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_exhibit_id_fkey FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4781 (class 2606 OID 16628)
-- Name: employee_exhibit employee_exhibit_exhibit_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_exhibit_id_fkey1 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4782 (class 2606 OID 16688)
-- Name: employee_exhibit employee_exhibit_exhibit_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_exhibit_id_fkey2 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4783 (class 2606 OID 16748)
-- Name: employee_exhibit employee_exhibit_exhibit_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_exhibit_id_fkey3 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4784 (class 2606 OID 16823)
-- Name: employee_exhibit employee_exhibit_exhibit_id_fkey4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_exhibit
    ADD CONSTRAINT employee_exhibit_exhibit_id_fkey4 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4767 (class 2606 OID 16618)
-- Name: enclosure_employee enclosure_employee_employee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4768 (class 2606 OID 16678)
-- Name: enclosure_employee enclosure_employee_employee_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_employee_id_fkey1 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4769 (class 2606 OID 16738)
-- Name: enclosure_employee enclosure_employee_employee_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_employee_id_fkey2 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4770 (class 2606 OID 16813)
-- Name: enclosure_employee enclosure_employee_employee_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_employee_id_fkey3 FOREIGN KEY (employee_id) REFERENCES public.employee(id) NOT VALID;


--
-- TOC entry 4771 (class 2606 OID 16555)
-- Name: enclosure_employee enclosure_employee_enclosure_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_enclosure_id_fkey FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4772 (class 2606 OID 16613)
-- Name: enclosure_employee enclosure_employee_enclosure_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_enclosure_id_fkey1 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4773 (class 2606 OID 16673)
-- Name: enclosure_employee enclosure_employee_enclosure_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_enclosure_id_fkey2 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4774 (class 2606 OID 16733)
-- Name: enclosure_employee enclosure_employee_enclosure_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_enclosure_id_fkey3 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4775 (class 2606 OID 16808)
-- Name: enclosure_employee enclosure_employee_enclosure_id_fkey4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enclosure_employee
    ADD CONSTRAINT enclosure_employee_enclosure_id_fkey4 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4761 (class 2606 OID 16803)
-- Name: food_dinosaur food_dinosaur_dinosaur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_dinosaur_id_fkey FOREIGN KEY (dinosaur_id) REFERENCES public.dinosaur(id) NOT VALID;


--
-- TOC entry 4762 (class 2606 OID 16545)
-- Name: food_dinosaur food_dinosaur_food_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_food_id_fkey FOREIGN KEY (food_id) REFERENCES public.food(id) NOT VALID;


--
-- TOC entry 4763 (class 2606 OID 16603)
-- Name: food_dinosaur food_dinosaur_food_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_food_id_fkey1 FOREIGN KEY (food_id) REFERENCES public.food(id) NOT VALID;


--
-- TOC entry 4764 (class 2606 OID 16663)
-- Name: food_dinosaur food_dinosaur_food_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_food_id_fkey2 FOREIGN KEY (food_id) REFERENCES public.food(id) NOT VALID;


--
-- TOC entry 4765 (class 2606 OID 16723)
-- Name: food_dinosaur food_dinosaur_food_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_food_id_fkey3 FOREIGN KEY (food_id) REFERENCES public.food(id) NOT VALID;


--
-- TOC entry 4766 (class 2606 OID 16798)
-- Name: food_dinosaur food_dinosaur_food_id_fkey4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_dinosaur
    ADD CONSTRAINT food_dinosaur_food_id_fkey4 FOREIGN KEY (food_id) REFERENCES public.food(id) NOT VALID;


--
-- TOC entry 4791 (class 2606 OID 16580)
-- Name: tour_enclosure tour_enclosure_enclosure_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_enclosure_id_fkey FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4792 (class 2606 OID 16648)
-- Name: tour_enclosure tour_enclosure_enclosure_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_enclosure_id_fkey1 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4793 (class 2606 OID 16708)
-- Name: tour_enclosure tour_enclosure_enclosure_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_enclosure_id_fkey2 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4794 (class 2606 OID 16768)
-- Name: tour_enclosure tour_enclosure_enclosure_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_enclosure_id_fkey3 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4795 (class 2606 OID 16843)
-- Name: tour_enclosure tour_enclosure_enclosure_id_fkey4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_enclosure_id_fkey4 FOREIGN KEY (enclosure_id) REFERENCES public.enclosure(id) NOT VALID;


--
-- TOC entry 4796 (class 2606 OID 16838)
-- Name: tour_enclosure tour_enclosure_tour_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_enclosure
    ADD CONSTRAINT tour_enclosure_tour_id_fkey FOREIGN KEY (tour_id) REFERENCES public.tour(id) NOT VALID;


--
-- TOC entry 4785 (class 2606 OID 16570)
-- Name: tour_exhibit tour_exhibit_exhibit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_exhibit_id_fkey FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4786 (class 2606 OID 16638)
-- Name: tour_exhibit tour_exhibit_exhibit_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_exhibit_id_fkey1 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4787 (class 2606 OID 16698)
-- Name: tour_exhibit tour_exhibit_exhibit_id_fkey2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_exhibit_id_fkey2 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4788 (class 2606 OID 16758)
-- Name: tour_exhibit tour_exhibit_exhibit_id_fkey3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_exhibit_id_fkey3 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4789 (class 2606 OID 16833)
-- Name: tour_exhibit tour_exhibit_exhibit_id_fkey4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_exhibit_id_fkey4 FOREIGN KEY (exhibit_id) REFERENCES public.exhibit(id) NOT VALID;


--
-- TOC entry 4790 (class 2606 OID 16828)
-- Name: tour_exhibit tour_exhibit_tour_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_exhibit
    ADD CONSTRAINT tour_exhibit_tour_id_fkey FOREIGN KEY (tour_id) REFERENCES public.tour(id) NOT VALID;


--
-- TOC entry 4798 (class 2606 OID 16793)
-- Name: tour tour_visitor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour
    ADD CONSTRAINT tour_visitor_id_fkey FOREIGN KEY (visitor_id) REFERENCES public.visitor(id) NOT VALID;


-- Completed on 2025-02-25 07:42:52

--
-- PostgreSQL database dump complete
--

