CREATE TABLE IF NOT EXISTS public.food
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price money NOT NULL,
    species character varying,
    composition text NOT NULL,
    amount real,
    PRIMARY KEY (id)
);

CREATE TABLE public.dinosaur
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    species character varying NOT NULL,
    gender character varying NOT NULL,
    max_speed real,
    weight real,
    height real,
	enclosure_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enclosure
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    square real NOT NULL,
    location character varying NOT NULL,
    height real,
    capacity integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.tour
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    duration time without time zone,
    price money NOT NULL,
	visitor_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.visitor
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    gender character varying NOT NULL,
    age integer,
    ticket integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    gender character varying NOT NULL,
    age integer,
    "position" character varying NOT NULL,
    experience integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exhibit
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description text,
    type character varying,
    date date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.food_dinosaur
(
    food_id integer NOT NULL,
    dinosaur_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.enclosure_employee
(
    enclosure_id integer NOT NULL,
    employee_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.employee_exhibit
(
    employee_id integer NOT NULL,
    exhibit_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tour_exhibit
(
    tour_id integer NOT NULL,
    exhibit_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tour_enclosure
(
    tour_id integer NOT NULL,
    enclosure_id integer NOT NULL
);

ALTER TABLE IF EXISTS public.dinosaur
    ADD FOREIGN KEY (enclosure_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour
    ADD FOREIGN KEY (visitor_id)
    REFERENCES public.visitor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.food_dinosaur
    ADD FOREIGN KEY (food_id)
    REFERENCES public.food (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.food_dinosaur
    ADD FOREIGN KEY (dinosaur_id)
    REFERENCES public.dinosaur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enclosure_employee
    ADD FOREIGN KEY (enclosure_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enclosure_employee
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_exhibit
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_exhibit
    ADD FOREIGN KEY (exhibit_id)
    REFERENCES public.exhibit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_exhibit
    ADD FOREIGN KEY (tour_id)
    REFERENCES public.tour (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_exhibit
    ADD FOREIGN KEY (exhibit_id)
    REFERENCES public.exhibit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_enclosure
    ADD FOREIGN KEY (tour_id)
    REFERENCES public.tour (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_enclosure
    ADD FOREIGN KEY (enclosure_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


