-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.food
(
    id integer,
    price money,
    species character varying,
    composition text,
    amount real,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dinosaur
(
    id integer,
    name character varying NOT NULL,
    species character varying,
    gender character varying,
    max_speed real,
    weight real,
    height real,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enclosure
(
    id integer,
    square real,
    location character varying,
    height real,
    capacity integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tour
(
    id integer,
    date date,
    "time" time without time zone,
    duration time without time zone,
    price money,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.visitor
(
    id integer,
    name character varying,
    gender character varying,
    age integer,
    ticket integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id integer,
    name character varying,
    gender character varying,
    age integer,
    "position" character varying,
    experience integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exhibit
(
    id integer,
    name character varying,
    description text,
    date date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.food_dinosaur
(
    food_id integer,
    dinosaur_id integer
);

CREATE TABLE IF NOT EXISTS public.enclosure_employee
(
    enclosure_id integer,
    employee_id integer
);

CREATE TABLE IF NOT EXISTS public.employee_exhibit
(
    employee_id integer,
    exhibit_id integer
);

CREATE TABLE IF NOT EXISTS public.tour_exhibit
(
    tour_id integer,
    exhibit_id integer
);

CREATE TABLE IF NOT EXISTS public.tour_enclosure
(
    tour_id integer,
    enclosure_id integer
);

ALTER TABLE IF EXISTS public.dinosaur
    ADD FOREIGN KEY (dinosaur_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour
    ADD FOREIGN KEY (id)
    REFERENCES public.visitor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.food_dinosaur
    ADD FOREIGN KEY (food_id)
    REFERENCES public.food (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.food_dinosaur
    ADD FOREIGN KEY (dinosaur_id)
    REFERENCES public.dinosaur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enclosure_employee
    ADD FOREIGN KEY (enclosure_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enclosure_employee
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_exhibit
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_exhibit
    ADD FOREIGN KEY (exhibit_id)
    REFERENCES public.exhibit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_exhibit
    ADD FOREIGN KEY (tour_id)
    REFERENCES public.tour (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_exhibit
    ADD FOREIGN KEY (exhibit_id)
    REFERENCES public.exhibit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_enclosure
    ADD FOREIGN KEY (tour_id)
    REFERENCES public.tour (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tour_enclosure
    ADD FOREIGN KEY (enclosure_id)
    REFERENCES public.enclosure (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;